name: Build

on:
  workflow_dispatch:

permissions:
  contents: write


jobs:

  sort:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install depedencies
      run: |
        sudo apt install git devscripts build-essential debhelper dh-make pbuilder fakeroot lintian sbuild dput gnupg
    - name: Fetch Chromium Debian Source, Apply patches
      run: |
        # Fetch Chromium Debian Source, and create our own branches (debian for stock, ubuntu for modifications)
        git init
        git remote add upstream https://salsa.debian.org/chromium-team/chromium.git
        git fetch upstream master
        git fetch origin --prune
        git checkout -B debian upstream/master
        git push origin debian --force-with-lease
        git checkout debian
        git checkout -B ubuntu
        # delete the master_preferences
        git checkout ubuntu
        git rm -f debian/etc/master_preferences || true
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git diff --quiet && git diff --staged --quiet || git commit -m "Drop Debian master_preferences to keep Chromium stock"
        git push origin ubuntu --force
    - name : Build Source Package
      run: |
        set -x
        # Config SSH
        #mkdir -p ~/.ssh
        #printf "%s\n" "${SSHKEY_PRIV}" > ~/.ssh/id_ed25519
        #sudo chmod 600 ~/.ssh/id_ed25519
        #ssh-keyscan -H launchpad.net >> ~/.ssh/known_hosts
        # config PGP
        echo "$GPG_KEY" | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG
        # Start Build
        git checkout ubuntu
        debuild -S -sa --no-tgz-check -k"${GPG_SEC}" -p"gpg --batch --passphrase ${GPG_PASS} --pinentry-mode loopback"
        dput ppa:arfshl/chromium-ubuntu-deb  ../chromium_*.changes
      env: 
        GPG_KEY: ${{ secrets.GPG_KEY }}
        GPG_PASS: ${{ secrets.GPG_PASS }}
        GPG_SEC: ${{ secrets.GPG_SEC }}
        SSHKEY_PRIV: ${{ secrets.SSHKEY_PRIV }}
